# Generated by Django 5.2.6 on 2025-09-13 22:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_department_is_active_project_expected_beneficiaries_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FundAllocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=15)),
                ('allocation_type', models.CharField(choices=[('initial', 'Initial Allocation'), ('additional', 'Additional Funding'), ('adjustment', 'Budget Adjustment'), ('reallocation', 'Fund Reallocation')], default='initial', max_length=20)),
                ('source', models.CharField(help_text='Source of the funding', max_length=200)),
                ('description', models.TextField(help_text='Description of the allocation')),
                ('status', models.CharField(choices=[('pending', 'Pending Approval'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('active', 'Active')], default='pending', max_length=20)),
                ('allocation_date', models.DateField(help_text='Date when allocation was made')),
                ('effective_date', models.DateField(help_text='Date when allocation becomes effective')),
                ('supporting_documents', models.TextField(blank=True, help_text='References to supporting documents')),
                ('notes', models.TextField(blank=True, help_text='Additional notes')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('allocated_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='allocated_funds', to=settings.AUTH_USER_MODEL)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_funds', to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fund_allocations', to='core.project')),
            ],
            options={
                'verbose_name': 'Fund Allocation',
                'verbose_name_plural': 'Fund Allocations',
                'ordering': ['-created_at'],
            },
        ),
    ]
