# Generated by Django 5.2.6 on 2025-09-13 22:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_fundallocation'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectSpending',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=15)),
                ('description', models.TextField()),
                ('category', models.CharField(choices=[('equipment', 'Equipment'), ('materials', 'Materials'), ('labor', 'Labor'), ('services', 'Services'), ('travel', 'Travel'), ('utilities', 'Utilities'), ('other', 'Other')], max_length=20)),
                ('transaction_date', models.DateField()),
                ('supporting_documents', models.TextField(blank=True, help_text='References to supporting documents')),
                ('status', models.CharField(choices=[('pending', 'Pending Approval'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('rejection_reason', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_spending', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_spending', to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='spending_records', to='core.project')),
            ],
            options={
                'verbose_name': 'Project Spending',
                'verbose_name_plural': 'Project Spending Records',
                'ordering': ['-transaction_date', '-created_at'],
            },
        ),
    ]
